FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_MQTT_BROKER_URL
ARG VITE_MQTT_TOPIC
ARG VITE_MQTT_USERNAME
ARG VITE_MQTT_PASSWORD
ARG VITE_MQTT_CLIENT_PREFIX
ARG VITE_DEFAULT_ROOM
ENV VITE_MQTT_BROKER_URL=$VITE_MQTT_BROKER_URL \
    VITE_MQTT_TOPIC=$VITE_MQTT_TOPIC \
    VITE_MQTT_USERNAME=$VITE_MQTT_USERNAME \
    VITE_MQTT_PASSWORD=$VITE_MQTT_PASSWORD \
    VITE_MQTT_CLIENT_PREFIX=$VITE_MQTT_CLIENT_PREFIX \
    VITE_DEFAULT_ROOM=$VITE_DEFAULT_ROOM

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]